# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notification_service/notification_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'notification_service/notification_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/notification_service/notification_service.proto\x12\x0cnotification\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bgoogle/protobuf/empty.proto\"x\n\x18SendPushFromUsersRequest\x12(\n\x07message\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x10\n\x08user_ids\x18\x02 \x03(\x03\x12\x14\n\x07is_base\x18\x03 \x01(\x08H\x00\x88\x01\x01\x42\n\n\x08_is_base2j\n\x13NotificationService\x12S\n\x11SendPushFromUsers\x12&.notification.SendPushFromUsersRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notification_service.notification_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDPUSHFROMUSERSREQUEST']._serialized_start=124
  _globals['_SENDPUSHFROMUSERSREQUEST']._serialized_end=244
  _globals['_NOTIFICATIONSERVICE']._serialized_start=246
  _globals['_NOTIFICATIONSERVICE']._serialized_end=352
# @@protoc_insertion_point(module_scope)
