"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.struct_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class SendPushFromUsersRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    USER_IDS_FIELD_NUMBER: builtins.int
    IS_BASE_FIELD_NUMBER: builtins.int
    is_base: builtins.bool
    @property
    def message(self) -> google.protobuf.struct_pb2.Struct: ...
    @property
    def user_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        message: google.protobuf.struct_pb2.Struct | None = ...,
        user_ids: collections.abc.Iterable[builtins.int] | None = ...,
        is_base: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_is_base", b"_is_base", "is_base", b"is_base", "message", b"message"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_is_base", b"_is_base", "is_base", b"is_base", "message", b"message", "user_ids", b"user_ids"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_is_base", b"_is_base"]) -> typing.Literal["is_base"] | None: ...

global___SendPushFromUsersRequest = SendPushFromUsersRequest
