# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos.ai_service import ai_service_pb2 as protos_dot_ai__service_dot_ai__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protos/ai_service/ai_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIAssistantStub(object):
    """Service definition for the AI Assistant
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ImproveText = channel.unary_unary(
                '/assistant.AIAssistant/ImproveText',
                request_serializer=protos_dot_ai__service_dot_ai__service__pb2.ImproveTextRequest.SerializeToString,
                response_deserializer=protos_dot_ai__service_dot_ai__service__pb2.TextResponse.FromString,
                _registered_method=True)
        self.AIChat = channel.unary_unary(
                '/assistant.AIAssistant/AIChat',
                request_serializer=protos_dot_ai__service_dot_ai__service__pb2.AIChatRequest.SerializeToString,
                response_deserializer=protos_dot_ai__service_dot_ai__service__pb2.TextResponse.FromString,
                _registered_method=True)
        self.CustomTemplate = channel.unary_unary(
                '/assistant.AIAssistant/CustomTemplate',
                request_serializer=protos_dot_ai__service_dot_ai__service__pb2.CustomTemplateRequest.SerializeToString,
                response_deserializer=protos_dot_ai__service_dot_ai__service__pb2.TextResponse.FromString,
                _registered_method=True)


class AIAssistantServicer(object):
    """Service definition for the AI Assistant
    """

    def ImproveText(self, request, context):
        """Improves text using AI
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AIChat(self, request, context):
        """Performs chat with AI
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CustomTemplate(self, request, context):
        """Generates a custom document template
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIAssistantServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ImproveText': grpc.unary_unary_rpc_method_handler(
                    servicer.ImproveText,
                    request_deserializer=protos_dot_ai__service_dot_ai__service__pb2.ImproveTextRequest.FromString,
                    response_serializer=protos_dot_ai__service_dot_ai__service__pb2.TextResponse.SerializeToString,
            ),
            'AIChat': grpc.unary_unary_rpc_method_handler(
                    servicer.AIChat,
                    request_deserializer=protos_dot_ai__service_dot_ai__service__pb2.AIChatRequest.FromString,
                    response_serializer=protos_dot_ai__service_dot_ai__service__pb2.TextResponse.SerializeToString,
            ),
            'CustomTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.CustomTemplate,
                    request_deserializer=protos_dot_ai__service_dot_ai__service__pb2.CustomTemplateRequest.FromString,
                    response_serializer=protos_dot_ai__service_dot_ai__service__pb2.TextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'assistant.AIAssistant', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('assistant.AIAssistant', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIAssistant(object):
    """Service definition for the AI Assistant
    """

    @staticmethod
    def ImproveText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/assistant.AIAssistant/ImproveText',
            protos_dot_ai__service_dot_ai__service__pb2.ImproveTextRequest.SerializeToString,
            protos_dot_ai__service_dot_ai__service__pb2.TextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AIChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/assistant.AIAssistant/AIChat',
            protos_dot_ai__service_dot_ai__service__pb2.AIChatRequest.SerializeToString,
            protos_dot_ai__service_dot_ai__service__pb2.TextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CustomTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/assistant.AIAssistant/CustomTemplate',
            protos_dot_ai__service_dot_ai__service__pb2.CustomTemplateRequest.SerializeToString,
            protos_dot_ai__service_dot_ai__service__pb2.TextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
